### ISSUE TITLE
Повышение планки оценивания диплома

### ISSUE THREAD

**Issue by GeorgiyDemo** [GENDOSMAL/Diplom#1]
Предлагаю выкинуть проектирование и интеграцию приложения под Andorid в связи с тем, что данная разработка повышает среднестатистический уровень работ в нашем колледже

Мной со @SkylinSky было принято решение рассмотреть это как баг.

**Comment by GENDOSMAL** [comment]
Оно не сложное и сделано будет просто для объема и то не факт.
